# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1026, 531)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mplCanvas = MplCanvasWrapper(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplCanvas.sizePolicy().hasHeightForWidth())
        self.mplCanvas.setSizePolicy(sizePolicy)
        self.mplCanvas.setMinimumSize(QtCore.QSize(400, 250))
        self.mplCanvas.setObjectName(_fromUtf8("mplCanvas"))
        self.gridLayout_3.addWidget(self.mplCanvas, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lShowTime = QtGui.QLabel(self.frame_3)
        self.lShowTime.setMinimumSize(QtCore.QSize(46, 0))
        self.lShowTime.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lShowTime.setFrameShape(QtGui.QFrame.Panel)
        self.lShowTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowTime.setObjectName(_fromUtf8("lShowTime"))
        self.gridLayout.addWidget(self.lShowTime, 1, 5, 1, 1)
        self.lTime2 = QtGui.QLabel(self.frame_3)
        self.lTime2.setObjectName(_fromUtf8("lTime2"))
        self.gridLayout.addWidget(self.lTime2, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.lTime1 = QtGui.QLabel(self.frame_3)
        self.lTime1.setObjectName(_fromUtf8("lTime1"))
        self.gridLayout.addWidget(self.lTime1, 2, 3, 1, 1)
        self.lEfit = QtGui.QLabel(self.frame_3)
        self.lEfit.setObjectName(_fromUtf8("lEfit"))
        self.gridLayout.addWidget(self.lEfit, 1, 0, 1, 1)
        self.lShot1 = QtGui.QLabel(self.frame_3)
        self.lShot1.setObjectName(_fromUtf8("lShot1"))
        self.gridLayout.addWidget(self.lShot1, 2, 0, 1, 1)
        self.sShot = QtGui.QSpinBox(self.frame_3)
        self.sShot.setMaximum(100000)
        self.sShot.setProperty("value", 100000)
        self.sShot.setObjectName(_fromUtf8("sShot"))
        self.gridLayout.addWidget(self.sShot, 2, 1, 1, 2)
        self.sTime = QtGui.QSpinBox(self.frame_3)
        self.sTime.setMaximum(100000)
        self.sTime.setProperty("value", 3000)
        self.sTime.setObjectName(_fromUtf8("sTime"))
        self.gridLayout.addWidget(self.sTime, 2, 4, 1, 1)
        self.bPlot = QtGui.QPushButton(self.frame_3)
        self.bPlot.setObjectName(_fromUtf8("bPlot"))
        self.gridLayout.addWidget(self.bPlot, 2, 5, 1, 2)
        self.lShowShot = QtGui.QLabel(self.frame_3)
        self.lShowShot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lShowShot.setFrameShape(QtGui.QFrame.Panel)
        self.lShowShot.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowShot.setObjectName(_fromUtf8("lShowShot"))
        self.gridLayout.addWidget(self.lShowShot, 1, 2, 1, 2)
        self.lShot2 = QtGui.QLabel(self.frame_3)
        self.lShot2.setObjectName(_fromUtf8("lShot2"))
        self.gridLayout.addWidget(self.lShot2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(321, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(65, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 7, 1, 1)
        self.bSave = QtGui.QPushButton(self.frame_3)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.gridLayout.addWidget(self.bSave, 2, 8, 1, 1)
        self.cRhoPsi = QtGui.QComboBox(self.frame_3)
        self.cRhoPsi.setObjectName(_fromUtf8("cRhoPsi"))
        self.cRhoPsi.addItem(_fromUtf8(""))
        self.cRhoPsi.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cRhoPsi, 1, 8, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.bManFit = QtGui.QPushButton(self.tab_3)
        self.bManFit.setGeometry(QtCore.QRect(170, 180, 81, 31))
        self.bManFit.setObjectName(_fromUtf8("bManFit"))
        self.sKnotsNum = QtGui.QSlider(self.tab_3)
        self.sKnotsNum.setGeometry(QtCore.QRect(119, 140, 131, 20))
        self.sKnotsNum.setMinimum(5)
        self.sKnotsNum.setMaximum(9)
        self.sKnotsNum.setPageStep(1)
        self.sKnotsNum.setProperty("value", 5)
        self.sKnotsNum.setOrientation(QtCore.Qt.Horizontal)
        self.sKnotsNum.setObjectName(_fromUtf8("sKnotsNum"))
        self.lKnotsNum = QtGui.QLabel(self.tab_3)
        self.lKnotsNum.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.lKnotsNum.setObjectName(_fromUtf8("lKnotsNum"))
        self.lShowKnotsNum = QtGui.QLabel(self.tab_3)
        self.lShowKnotsNum.setGeometry(QtCore.QRect(180, 120, 68, 17))
        self.lShowKnotsNum.setScaledContents(True)
        self.lShowKnotsNum.setObjectName(_fromUtf8("lShowKnotsNum"))
        self.cbFunctionSelect = QtGui.QComboBox(self.tab_3)
        self.cbFunctionSelect.setGeometry(QtCore.QRect(50, 180, 91, 21))
        self.cbFunctionSelect.setObjectName(_fromUtf8("cbFunctionSelect"))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1026, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Help.addAction(self.action_About)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.sKnotsNum, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lShowKnotsNum.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Whatever Name", None))
        self.lShowTime.setText(_translate("MainWindow", "3000", None))
        self.lTime2.setText(_translate("MainWindow", "Time(msec):", None))
        self.label.setText(_translate("MainWindow", "Data Description:", None))
        self.lTime1.setText(_translate("MainWindow", "Time:", None))
        self.lEfit.setText(_translate("MainWindow", "Efit:", None))
        self.lShot1.setText(_translate("MainWindow", "Shot:", None))
        self.bPlot.setText(_translate("MainWindow", "Plot", None))
        self.lShowShot.setText(_translate("MainWindow", "100000", None))
        self.lShot2.setText(_translate("MainWindow", "Shot:", None))
        self.bSave.setText(_translate("MainWindow", "Save", None))
        self.cRhoPsi.setItemText(0, _translate("MainWindow", "rho", None))
        self.cRhoPsi.setItemText(1, _translate("MainWindow", "psi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "data control", None))
        self.bManFit.setText(_translate("MainWindow", "Manual Fit", None))
        self.lKnotsNum.setText(_translate("MainWindow", "Number of knots:", None))
        self.lShowKnotsNum.setText(_translate("MainWindow", "5", None))
        self.cbFunctionSelect.setItemText(0, _translate("MainWindow", "tanh_multi", None))
        self.cbFunctionSelect.setItemText(1, _translate("MainWindow", "tanh_0out", None))
        self.cbFunctionSelect.setItemText(2, _translate("MainWindow", "tsplfun", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "fit control", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_About.setShortcut(_translate("MainWindow", "Alt+A", None))

from mplCanvasWrapper import MplCanvasWrapper
