# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectefitwidgetne.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SelectEfitNe(object):
    def setupUi(self, SelectEfitNe):
        SelectEfitNe.setObjectName(_fromUtf8("SelectEfitNe"))
        SelectEfitNe.resize(473, 516)
        self.gridLayout_2 = QtGui.QGridLayout(SelectEfitNe)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 87, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.frame = QtGui.QFrame(SelectEfitNe)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.rbFile = QtGui.QRadioButton(self.frame)
        self.rbFile.setChecked(True)
        self.rbFile.setObjectName(_fromUtf8("rbFile"))
        self.gridLayout_7.addWidget(self.rbFile, 0, 1, 1, 1)
        self.rbMdsPlus = QtGui.QRadioButton(self.frame)
        self.rbMdsPlus.setObjectName(_fromUtf8("rbMdsPlus"))
        self.gridLayout_7.addWidget(self.rbMdsPlus, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(SelectEfitNe)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbRZMap = QtGui.QRadioButton(self.frame_2)
        self.rbRZMap.setChecked(True)
        self.rbRZMap.setObjectName(_fromUtf8("rbRZMap"))
        self.verticalLayout.addWidget(self.rbRZMap)
        self.rbRhoMap = QtGui.QRadioButton(self.frame_2)
        self.rbRhoMap.setObjectName(_fromUtf8("rbRhoMap"))
        self.verticalLayout.addWidget(self.rbRhoMap)
        self.rbPsiMap = QtGui.QRadioButton(self.frame_2)
        self.rbPsiMap.setObjectName(_fromUtf8("rbPsiMap"))
        self.verticalLayout.addWidget(self.rbPsiMap)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 1, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lGFileDir = QtGui.QLabel(self.frame_2)
        self.lGFileDir.setObjectName(_fromUtf8("lGFileDir"))
        self.horizontalLayout_2.addWidget(self.lGFileDir)
        self.leGFileDir = QtGui.QLineEdit(self.frame_2)
        self.leGFileDir.setDragEnabled(True)
        self.leGFileDir.setObjectName(_fromUtf8("leGFileDir"))
        self.horizontalLayout_2.addWidget(self.leGFileDir)
        self.tbGFileDir = QtGui.QToolButton(self.frame_2)
        self.tbGFileDir.setObjectName(_fromUtf8("tbGFileDir"))
        self.horizontalLayout_2.addWidget(self.tbGFileDir)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lDataDir = QtGui.QLabel(self.frame_2)
        self.lDataDir.setObjectName(_fromUtf8("lDataDir"))
        self.horizontalLayout_3.addWidget(self.lDataDir)
        self.leDataDir = QtGui.QLineEdit(self.frame_2)
        self.leDataDir.setDragEnabled(True)
        self.leDataDir.setObjectName(_fromUtf8("leDataDir"))
        self.horizontalLayout_3.addWidget(self.leDataDir)
        self.tbData = QtGui.QToolButton(self.frame_2)
        self.tbData.setObjectName(_fromUtf8("tbData"))
        self.horizontalLayout_3.addWidget(self.tbData)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(SelectEfitNe)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.diagnostics2 = QtGui.QCheckBox(self.frame_3)
        self.diagnostics2.setObjectName(_fromUtf8("diagnostics2"))
        self.gridLayout_5.addWidget(self.diagnostics2, 2, 0, 1, 1)
        self.diagnostics1 = QtGui.QCheckBox(self.frame_3)
        self.diagnostics1.setObjectName(_fromUtf8("diagnostics1"))
        self.gridLayout_5.addWidget(self.diagnostics1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 3, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(SelectEfitNe)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.frame_4)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spbShot = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbShot.sizePolicy().hasHeightForWidth())
        self.spbShot.setSizePolicy(sizePolicy)
        self.spbShot.setMaximum(100000)
        self.spbShot.setObjectName(_fromUtf8("spbShot"))
        self.gridLayout.addWidget(self.spbShot, 0, 0, 1, 1)
        self.bUpdate = QtGui.QPushButton(self.groupBox)
        self.bUpdate.setObjectName(_fromUtf8("bUpdate"))
        self.gridLayout.addWidget(self.bUpdate, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.treeLayout = QtGui.QVBoxLayout()
        self.treeLayout.setSpacing(0)
        self.treeLayout.setObjectName(_fromUtf8("treeLayout"))
        self.lTree = QtGui.QLabel(self.frame_4)
        self.lTree.setFrameShape(QtGui.QFrame.Panel)
        self.lTree.setFrameShadow(QtGui.QFrame.Raised)
        self.lTree.setAlignment(QtCore.Qt.AlignCenter)
        self.lTree.setObjectName(_fromUtf8("lTree"))
        self.treeLayout.addWidget(self.lTree)
        self.listTree = QtGui.QListWidget(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listTree.sizePolicy().hasHeightForWidth())
        self.listTree.setSizePolicy(sizePolicy)
        self.listTree.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listTree.setFrameShape(QtGui.QFrame.Panel)
        self.listTree.setObjectName(_fromUtf8("listTree"))
        self.treeLayout.addWidget(self.listTree)
        self.horizontalLayout.addLayout(self.treeLayout)
        self.timeLayout = QtGui.QVBoxLayout()
        self.timeLayout.setSpacing(0)
        self.timeLayout.setObjectName(_fromUtf8("timeLayout"))
        self.lTime = QtGui.QLabel(self.frame_4)
        self.lTime.setFrameShape(QtGui.QFrame.Panel)
        self.lTime.setFrameShadow(QtGui.QFrame.Raised)
        self.lTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lTime.setObjectName(_fromUtf8("lTime"))
        self.timeLayout.addWidget(self.lTime)
        self.listTime = QtGui.QListWidget(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listTime.sizePolicy().hasHeightForWidth())
        self.listTime.setSizePolicy(sizePolicy)
        self.listTime.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listTime.setFrameShape(QtGui.QFrame.Panel)
        self.listTime.setObjectName(_fromUtf8("listTime"))
        self.timeLayout.addWidget(self.listTime)
        self.horizontalLayout.addLayout(self.timeLayout)
        spacerItem1 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 1)

        self.retranslateUi(SelectEfitNe)
        QtCore.QObject.connect(self.rbFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.show)
        QtCore.QObject.connect(self.rbFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_3.hide)
        QtCore.QObject.connect(self.rbMdsPlus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.hide)
        QtCore.QObject.connect(self.rbMdsPlus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_3.show)
        QtCore.QObject.connect(self.rbFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_4.hide)
        QtCore.QObject.connect(self.rbMdsPlus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_4.show)
        QtCore.QMetaObject.connectSlotsByName(SelectEfitNe)

    def retranslateUi(self, SelectEfitNe):
        self.label.setText(_translate("SelectEfitNe", "Select Efit From:", None))
        self.rbFile.setText(_translate("SelectEfitNe", "File", None))
        self.rbMdsPlus.setText(_translate("SelectEfitNe", "MDS+ Server", None))
        self.rbRZMap.setText(_translate("SelectEfitNe", "RZ Map", None))
        self.rbRhoMap.setText(_translate("SelectEfitNe", "Rho Map", None))
        self.rbPsiMap.setText(_translate("SelectEfitNe", "Psi Map", None))
        self.lGFileDir.setText(_translate("SelectEfitNe", "GFile Dir:", None))
        self.tbGFileDir.setText(_translate("SelectEfitNe", "...", None))
        self.lDataDir.setText(_translate("SelectEfitNe", "Data  Dir:", None))
        self.tbData.setText(_translate("SelectEfitNe", "...", None))
        self.diagnostics2.setText(_translate("SelectEfitNe", "Thomson (Core)", None))
        self.diagnostics1.setText(_translate("SelectEfitNe", "Reflectometry", None))
        self.groupBox.setTitle(_translate("SelectEfitNe", "Shot", None))
        self.bUpdate.setText(_translate("SelectEfitNe", "Update", None))
        self.lTree.setText(_translate("SelectEfitNe", "Tree", None))
        self.lTime.setText(_translate("SelectEfitNe", "Time", None))

