# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog9.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog9(object):
    def setupUi(self, Dialog9):
        Dialog9.setObjectName(_fromUtf8("Dialog9"))
        Dialog9.resize(680, 339)
        Dialog9.setMinimumSize(QtCore.QSize(680, 339))
        Dialog9.setMaximumSize(QtCore.QSize(680, 339))
        Dialog9.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog9)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.controlFrame = QtGui.QFrame(Dialog9)
        self.controlFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.controlFrame.setObjectName(_fromUtf8("controlFrame"))
        self.gridLayout = QtGui.QGridLayout(self.controlFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setVerticalSpacing(0)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.spb17 = QtGui.QSpinBox(self.controlFrame)
        self.spb17.setObjectName(_fromUtf8("spb17"))
        self.horizontalLayout_18.addWidget(self.spb17)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.spb18 = QtGui.QSpinBox(self.controlFrame)
        self.spb18.setObjectName(_fromUtf8("spb18"))
        self.horizontalLayout_18.addWidget(self.spb18)
        self.formLayout_9.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(16)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.lNm9 = QtGui.QLabel(self.controlFrame)
        self.lNm9.setObjectName(_fromUtf8("lNm9"))
        self.horizontalLayout_17.addWidget(self.lNm9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.lDig9 = QtGui.QLabel(self.controlFrame)
        self.lDig9.setObjectName(_fromUtf8("lDig9"))
        self.horizontalLayout_17.addWidget(self.lDig9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.chb9 = QtGui.QCheckBox(self.controlFrame)
        self.chb9.setText(_fromUtf8(""))
        self.chb9.setObjectName(_fromUtf8("chb9"))
        self.horizontalLayout_17.addWidget(self.chb9)
        self.formLayout_9.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_17)
        self.sld9 = QtGui.QSlider(self.controlFrame)
        self.sld9.setOrientation(QtCore.Qt.Horizontal)
        self.sld9.setObjectName(_fromUtf8("sld9"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld9)
        self.gridLayout.addLayout(self.formLayout_9, 2, 2, 1, 1)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setVerticalSpacing(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.spb13 = QtGui.QSpinBox(self.controlFrame)
        self.spb13.setObjectName(_fromUtf8("spb13"))
        self.horizontalLayout_14.addWidget(self.spb13)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.spb14 = QtGui.QSpinBox(self.controlFrame)
        self.spb14.setObjectName(_fromUtf8("spb14"))
        self.horizontalLayout_14.addWidget(self.spb14)
        self.formLayout_7.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(16)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lNm7 = QtGui.QLabel(self.controlFrame)
        self.lNm7.setObjectName(_fromUtf8("lNm7"))
        self.horizontalLayout_13.addWidget(self.lNm7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.lDig7 = QtGui.QLabel(self.controlFrame)
        self.lDig7.setObjectName(_fromUtf8("lDig7"))
        self.horizontalLayout_13.addWidget(self.lDig7)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.chb7 = QtGui.QCheckBox(self.controlFrame)
        self.chb7.setText(_fromUtf8(""))
        self.chb7.setObjectName(_fromUtf8("chb7"))
        self.horizontalLayout_13.addWidget(self.chb7)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_13)
        self.sld7 = QtGui.QSlider(self.controlFrame)
        self.sld7.setOrientation(QtCore.Qt.Horizontal)
        self.sld7.setObjectName(_fromUtf8("sld7"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld7)
        self.gridLayout.addLayout(self.formLayout_7, 2, 0, 1, 1)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setVerticalSpacing(0)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.spb15 = QtGui.QSpinBox(self.controlFrame)
        self.spb15.setObjectName(_fromUtf8("spb15"))
        self.horizontalLayout_16.addWidget(self.spb15)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.spb16 = QtGui.QSpinBox(self.controlFrame)
        self.spb16.setObjectName(_fromUtf8("spb16"))
        self.horizontalLayout_16.addWidget(self.spb16)
        self.formLayout_8.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(16)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lNm8 = QtGui.QLabel(self.controlFrame)
        self.lNm8.setObjectName(_fromUtf8("lNm8"))
        self.horizontalLayout_15.addWidget(self.lNm8)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.lDig8 = QtGui.QLabel(self.controlFrame)
        self.lDig8.setObjectName(_fromUtf8("lDig8"))
        self.horizontalLayout_15.addWidget(self.lDig8)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.chb8 = QtGui.QCheckBox(self.controlFrame)
        self.chb8.setText(_fromUtf8(""))
        self.chb8.setObjectName(_fromUtf8("chb8"))
        self.horizontalLayout_15.addWidget(self.chb8)
        self.formLayout_8.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_15)
        self.sld8 = QtGui.QSlider(self.controlFrame)
        self.sld8.setOrientation(QtCore.Qt.Horizontal)
        self.sld8.setObjectName(_fromUtf8("sld8"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld8)
        self.gridLayout.addLayout(self.formLayout_8, 2, 1, 1, 1)
        self.formLayout_1 = QtGui.QFormLayout()
        self.formLayout_1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_1.setVerticalSpacing(0)
        self.formLayout_1.setObjectName(_fromUtf8("formLayout_1"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setSpacing(16)
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.lNm1 = QtGui.QLabel(self.controlFrame)
        self.lNm1.setObjectName(_fromUtf8("lNm1"))
        self.horizontalLayout_1.addWidget(self.lNm1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem12)
        self.lDig1 = QtGui.QLabel(self.controlFrame)
        self.lDig1.setObjectName(_fromUtf8("lDig1"))
        self.horizontalLayout_1.addWidget(self.lDig1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem13)
        self.chb1 = QtGui.QCheckBox(self.controlFrame)
        self.chb1.setText(_fromUtf8(""))
        self.chb1.setObjectName(_fromUtf8("chb1"))
        self.horizontalLayout_1.addWidget(self.chb1)
        self.formLayout_1.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_1)
        self.sld1 = QtGui.QSlider(self.controlFrame)
        self.sld1.setOrientation(QtCore.Qt.Horizontal)
        self.sld1.setObjectName(_fromUtf8("sld1"))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.spb1 = QtGui.QSpinBox(self.controlFrame)
        self.spb1.setObjectName(_fromUtf8("spb1"))
        self.horizontalLayout_2.addWidget(self.spb1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.spb2 = QtGui.QSpinBox(self.controlFrame)
        self.spb2.setObjectName(_fromUtf8("spb2"))
        self.horizontalLayout_2.addWidget(self.spb2)
        self.formLayout_1.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.gridLayout.addLayout(self.formLayout_1, 0, 0, 1, 1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setVerticalSpacing(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.spb11 = QtGui.QSpinBox(self.controlFrame)
        self.spb11.setObjectName(_fromUtf8("spb11"))
        self.horizontalLayout_12.addWidget(self.spb11)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.spb12 = QtGui.QSpinBox(self.controlFrame)
        self.spb12.setObjectName(_fromUtf8("spb12"))
        self.horizontalLayout_12.addWidget(self.spb12)
        self.formLayout_6.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(16)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lNm6 = QtGui.QLabel(self.controlFrame)
        self.lNm6.setObjectName(_fromUtf8("lNm6"))
        self.horizontalLayout_11.addWidget(self.lNm6)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.lDig6 = QtGui.QLabel(self.controlFrame)
        self.lDig6.setObjectName(_fromUtf8("lDig6"))
        self.horizontalLayout_11.addWidget(self.lDig6)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.chb6 = QtGui.QCheckBox(self.controlFrame)
        self.chb6.setText(_fromUtf8(""))
        self.chb6.setObjectName(_fromUtf8("chb6"))
        self.horizontalLayout_11.addWidget(self.chb6)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_11)
        self.sld6 = QtGui.QSlider(self.controlFrame)
        self.sld6.setOrientation(QtCore.Qt.Horizontal)
        self.sld6.setObjectName(_fromUtf8("sld6"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld6)
        self.gridLayout.addLayout(self.formLayout_6, 1, 2, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spb3 = QtGui.QSpinBox(self.controlFrame)
        self.spb3.setObjectName(_fromUtf8("spb3"))
        self.horizontalLayout_4.addWidget(self.spb3)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.spb4 = QtGui.QSpinBox(self.controlFrame)
        self.spb4.setObjectName(_fromUtf8("spb4"))
        self.horizontalLayout_4.addWidget(self.spb4)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(16)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lNm2 = QtGui.QLabel(self.controlFrame)
        self.lNm2.setObjectName(_fromUtf8("lNm2"))
        self.horizontalLayout_3.addWidget(self.lNm2)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem22)
        self.lDig2 = QtGui.QLabel(self.controlFrame)
        self.lDig2.setObjectName(_fromUtf8("lDig2"))
        self.horizontalLayout_3.addWidget(self.lDig2)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem23)
        self.chb2 = QtGui.QCheckBox(self.controlFrame)
        self.chb2.setText(_fromUtf8(""))
        self.chb2.setObjectName(_fromUtf8("chb2"))
        self.horizontalLayout_3.addWidget(self.chb2)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.sld2 = QtGui.QSlider(self.controlFrame)
        self.sld2.setOrientation(QtCore.Qt.Horizontal)
        self.sld2.setObjectName(_fromUtf8("sld2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld2)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setVerticalSpacing(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.spb7 = QtGui.QSpinBox(self.controlFrame)
        self.spb7.setObjectName(_fromUtf8("spb7"))
        self.horizontalLayout_8.addWidget(self.spb7)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.spb8 = QtGui.QSpinBox(self.controlFrame)
        self.spb8.setObjectName(_fromUtf8("spb8"))
        self.horizontalLayout_8.addWidget(self.spb8)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(16)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lNm4 = QtGui.QLabel(self.controlFrame)
        self.lNm4.setObjectName(_fromUtf8("lNm4"))
        self.horizontalLayout_7.addWidget(self.lNm4)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem26)
        self.lDig4 = QtGui.QLabel(self.controlFrame)
        self.lDig4.setObjectName(_fromUtf8("lDig4"))
        self.horizontalLayout_7.addWidget(self.lDig4)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.chb4 = QtGui.QCheckBox(self.controlFrame)
        self.chb4.setText(_fromUtf8(""))
        self.chb4.setObjectName(_fromUtf8("chb4"))
        self.horizontalLayout_7.addWidget(self.chb4)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.sld4 = QtGui.QSlider(self.controlFrame)
        self.sld4.setOrientation(QtCore.Qt.Horizontal)
        self.sld4.setObjectName(_fromUtf8("sld4"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld4)
        self.gridLayout.addLayout(self.formLayout_4, 1, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.spb5 = QtGui.QSpinBox(self.controlFrame)
        self.spb5.setObjectName(_fromUtf8("spb5"))
        self.horizontalLayout_6.addWidget(self.spb5)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem29)
        self.spb6 = QtGui.QSpinBox(self.controlFrame)
        self.spb6.setObjectName(_fromUtf8("spb6"))
        self.horizontalLayout_6.addWidget(self.spb6)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lNm3 = QtGui.QLabel(self.controlFrame)
        self.lNm3.setObjectName(_fromUtf8("lNm3"))
        self.horizontalLayout_5.addWidget(self.lNm3)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem30)
        self.lDig3 = QtGui.QLabel(self.controlFrame)
        self.lDig3.setObjectName(_fromUtf8("lDig3"))
        self.horizontalLayout_5.addWidget(self.lDig3)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem31)
        self.chb3 = QtGui.QCheckBox(self.controlFrame)
        self.chb3.setText(_fromUtf8(""))
        self.chb3.setObjectName(_fromUtf8("chb3"))
        self.horizontalLayout_5.addWidget(self.chb3)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.sld3 = QtGui.QSlider(self.controlFrame)
        self.sld3.setOrientation(QtCore.Qt.Horizontal)
        self.sld3.setObjectName(_fromUtf8("sld3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld3)
        self.gridLayout.addLayout(self.formLayout_3, 0, 2, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setVerticalSpacing(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.spb9 = QtGui.QSpinBox(self.controlFrame)
        self.spb9.setObjectName(_fromUtf8("spb9"))
        self.horizontalLayout_10.addWidget(self.spb9)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem32)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem33)
        self.spb10 = QtGui.QSpinBox(self.controlFrame)
        self.spb10.setObjectName(_fromUtf8("spb10"))
        self.horizontalLayout_10.addWidget(self.spb10)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(16)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lNm5 = QtGui.QLabel(self.controlFrame)
        self.lNm5.setObjectName(_fromUtf8("lNm5"))
        self.horizontalLayout_9.addWidget(self.lNm5)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem34)
        self.lDig5 = QtGui.QLabel(self.controlFrame)
        self.lDig5.setObjectName(_fromUtf8("lDig5"))
        self.horizontalLayout_9.addWidget(self.lDig5)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem35)
        self.chb5 = QtGui.QCheckBox(self.controlFrame)
        self.chb5.setText(_fromUtf8(""))
        self.chb5.setObjectName(_fromUtf8("chb5"))
        self.horizontalLayout_9.addWidget(self.chb5)
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.sld5 = QtGui.QSlider(self.controlFrame)
        self.sld5.setOrientation(QtCore.Qt.Horizontal)
        self.sld5.setObjectName(_fromUtf8("sld5"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sld5)
        self.gridLayout.addLayout(self.formLayout_5, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.controlFrame, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog9)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog9)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog9.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog9.reject)
        QtCore.QObject.connect(self.sld1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig1.setNum)
        QtCore.QObject.connect(self.sld2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig2.setNum)
        QtCore.QObject.connect(self.sld3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig3.setNum)
        QtCore.QObject.connect(self.sld4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig4.setNum)
        QtCore.QObject.connect(self.sld5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig5.setNum)
        QtCore.QObject.connect(self.sld6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig6.setNum)
        QtCore.QObject.connect(self.sld7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig7.setNum)
        QtCore.QObject.connect(self.sld8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig8.setNum)
        QtCore.QObject.connect(self.sld9, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lDig9.setNum)
        QtCore.QMetaObject.connectSlotsByName(Dialog9)
        Dialog9.setTabOrder(self.buttonBox, self.sld1)
        Dialog9.setTabOrder(self.sld1, self.spb1)
        Dialog9.setTabOrder(self.spb1, self.spb2)
        Dialog9.setTabOrder(self.spb2, self.sld2)
        Dialog9.setTabOrder(self.sld2, self.spb3)
        Dialog9.setTabOrder(self.spb3, self.spb4)
        Dialog9.setTabOrder(self.spb4, self.sld3)
        Dialog9.setTabOrder(self.sld3, self.spb5)
        Dialog9.setTabOrder(self.spb5, self.spb6)
        Dialog9.setTabOrder(self.spb6, self.sld4)
        Dialog9.setTabOrder(self.sld4, self.spb7)
        Dialog9.setTabOrder(self.spb7, self.spb8)
        Dialog9.setTabOrder(self.spb8, self.sld5)
        Dialog9.setTabOrder(self.sld5, self.spb9)
        Dialog9.setTabOrder(self.spb9, self.spb10)
        Dialog9.setTabOrder(self.spb10, self.sld6)
        Dialog9.setTabOrder(self.sld6, self.spb11)
        Dialog9.setTabOrder(self.spb11, self.spb12)
        Dialog9.setTabOrder(self.spb12, self.sld7)
        Dialog9.setTabOrder(self.sld7, self.spb13)
        Dialog9.setTabOrder(self.spb13, self.spb14)
        Dialog9.setTabOrder(self.spb14, self.sld8)
        Dialog9.setTabOrder(self.sld8, self.spb15)
        Dialog9.setTabOrder(self.spb15, self.spb16)
        Dialog9.setTabOrder(self.spb16, self.chb8)
        Dialog9.setTabOrder(self.chb8, self.spb17)
        Dialog9.setTabOrder(self.spb17, self.spb18)
        Dialog9.setTabOrder(self.spb18, self.chb1)
        Dialog9.setTabOrder(self.chb1, self.chb2)
        Dialog9.setTabOrder(self.chb2, self.chb3)
        Dialog9.setTabOrder(self.chb3, self.chb4)
        Dialog9.setTabOrder(self.chb4, self.chb5)
        Dialog9.setTabOrder(self.chb5, self.chb6)
        Dialog9.setTabOrder(self.chb6, self.chb7)
        Dialog9.setTabOrder(self.chb7, self.sld9)
        Dialog9.setTabOrder(self.sld9, self.chb9)

    def retranslateUi(self, Dialog9):
        Dialog9.setWindowTitle(_translate("Dialog9", "Manual Fit", None))
        self.spb17.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb18.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm9.setToolTip(_translate("Dialog9", "QUADRATIC OUTER", None))
        self.lNm9.setText(_translate("Dialog9", "Param No.6", None))
        self.lDig9.setText(_translate("Dialog9", "TextLabel", None))
        self.chb9.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld9.setToolTip(_translate("Dialog9", "QUADRATIC OUTER", None))
        self.spb13.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb14.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm7.setToolTip(_translate("Dialog9", "CUBIC OR QUARTIC (IF ZERO DER) INNER", None))
        self.lNm7.setText(_translate("Dialog9", "Param No.6", None))
        self.lDig7.setText(_translate("Dialog9", "TextLabel", None))
        self.chb7.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld7.setToolTip(_translate("Dialog9", "CUBIC OR QUARTIC (IF ZERO DER) INNER", None))
        self.spb15.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb16.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm8.setToolTip(_translate("Dialog9", "SLOPE OUTER", None))
        self.lNm8.setText(_translate("Dialog9", "Param No.6", None))
        self.lDig8.setText(_translate("Dialog9", "TextLabel", None))
        self.chb8.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld8.setToolTip(_translate("Dialog9", "SLOPE OUTER", None))
        self.lNm1.setToolTip(_translate("Dialog9", "SYMMETRY POINT", None))
        self.lNm1.setText(_translate("Dialog9", "Param No.1", None))
        self.lDig1.setText(_translate("Dialog9", "TextLabel", None))
        self.chb1.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld1.setToolTip(_translate("Dialog9", "SYMMETRY POINT", None))
        self.spb1.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb2.setToolTip(_translate("Dialog9", "Min Value", None))
        self.spb11.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb12.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm6.setToolTip(_translate("Dialog9", "QUADRADIC OR CUBIC (IF ZERO DER) INNER", None))
        self.lNm6.setText(_translate("Dialog9", "Param No.6", None))
        self.lDig6.setText(_translate("Dialog9", "TextLabel", None))
        self.chb6.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld6.setToolTip(_translate("Dialog9", "QUADRADIC OR CUBIC (IF ZERO DER) INNER", None))
        self.spb3.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb4.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm2.setToolTip(_translate("Dialog9", "FULL WIDTH", None))
        self.lNm2.setText(_translate("Dialog9", "Param No.2", None))
        self.lDig2.setText(_translate("Dialog9", "TextLabel", None))
        self.chb2.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld2.setToolTip(_translate("Dialog9", "FULL WIDTH", None))
        self.spb7.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb8.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm4.setToolTip(_translate("Dialog9", "OFFSET", None))
        self.lNm4.setText(_translate("Dialog9", "Param No.4", None))
        self.lDig4.setText(_translate("Dialog9", "TextLabel", None))
        self.chb4.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld4.setToolTip(_translate("Dialog9", "OFFSET", None))
        self.spb5.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb6.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm3.setToolTip(_translate("Dialog9", "HEIGHT", None))
        self.lNm3.setText(_translate("Dialog9", "Param No.3", None))
        self.lDig3.setText(_translate("Dialog9", "TextLabel", None))
        self.chb3.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld3.setToolTip(_translate("Dialog9", "HEIGHT", None))
        self.spb9.setToolTip(_translate("Dialog9", "Max Value", None))
        self.spb10.setToolTip(_translate("Dialog9", "Min Value", None))
        self.lNm5.setToolTip(_translate("Dialog9", "SLOPE OR QUADRATIC (IF ZERO DER) INNER", None))
        self.lNm5.setText(_translate("Dialog9", "Param No.5", None))
        self.lDig5.setText(_translate("Dialog9", "TextLabel", None))
        self.chb5.setToolTip(_translate("Dialog9", "CHECKED FIXES THE PARAMETER\n"
"UNCHECKED MAKES THE PARAMETER FREE.", None))
        self.sld5.setToolTip(_translate("Dialog9", "SLOPE OR QUADRATIC (IF ZERO DER) INNER", None))

