# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed May  4 21:15:26 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1026, 531)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mplCanvas = MplCanvasWrapper(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplCanvas.sizePolicy().hasHeightForWidth())
        self.mplCanvas.setSizePolicy(sizePolicy)
        self.mplCanvas.setMinimumSize(QtCore.QSize(400, 250))
        self.mplCanvas.setObjectName(_fromUtf8("mplCanvas"))
        self.gridLayout_3.addWidget(self.mplCanvas, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lShowTime = QtGui.QLabel(self.frame_3)
        self.lShowTime.setMinimumSize(QtCore.QSize(46, 0))
        self.lShowTime.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lShowTime.setFrameShape(QtGui.QFrame.Panel)
        self.lShowTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowTime.setObjectName(_fromUtf8("lShowTime"))
        self.gridLayout.addWidget(self.lShowTime, 1, 5, 1, 1)
        self.lTime2 = QtGui.QLabel(self.frame_3)
        self.lTime2.setObjectName(_fromUtf8("lTime2"))
        self.gridLayout.addWidget(self.lTime2, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.lTime1 = QtGui.QLabel(self.frame_3)
        self.lTime1.setObjectName(_fromUtf8("lTime1"))
        self.gridLayout.addWidget(self.lTime1, 2, 3, 1, 1)
        self.lEfit = QtGui.QLabel(self.frame_3)
        self.lEfit.setObjectName(_fromUtf8("lEfit"))
        self.gridLayout.addWidget(self.lEfit, 1, 0, 1, 1)
        self.lShot1 = QtGui.QLabel(self.frame_3)
        self.lShot1.setObjectName(_fromUtf8("lShot1"))
        self.gridLayout.addWidget(self.lShot1, 2, 0, 1, 1)
        self.sShot = QtGui.QSpinBox(self.frame_3)
        self.sShot.setMaximum(100000)
        self.sShot.setProperty("value", 100000)
        self.sShot.setObjectName(_fromUtf8("sShot"))
        self.gridLayout.addWidget(self.sShot, 2, 1, 1, 2)
        self.sTime = QtGui.QSpinBox(self.frame_3)
        self.sTime.setMaximum(100000)
        self.sTime.setProperty("value", 3000)
        self.sTime.setObjectName(_fromUtf8("sTime"))
        self.gridLayout.addWidget(self.sTime, 2, 4, 1, 1)
        self.lShowShot = QtGui.QLabel(self.frame_3)
        self.lShowShot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lShowShot.setFrameShape(QtGui.QFrame.Panel)
        self.lShowShot.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowShot.setObjectName(_fromUtf8("lShowShot"))
        self.gridLayout.addWidget(self.lShowShot, 1, 2, 1, 2)
        self.lShot2 = QtGui.QLabel(self.frame_3)
        self.lShot2.setObjectName(_fromUtf8("lShot2"))
        self.gridLayout.addWidget(self.lShot2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(321, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(65, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 7, 1, 1)
        self.bSave = QtGui.QPushButton(self.frame_3)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.gridLayout.addWidget(self.bSave, 2, 8, 1, 1)
        self.cRhoPsi = QtGui.QComboBox(self.frame_3)
        self.cRhoPsi.setObjectName(_fromUtf8("cRhoPsi"))
        self.cRhoPsi.addItem(_fromUtf8(""))
        self.cRhoPsi.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cRhoPsi, 1, 8, 1, 1)
        self.bRePlot = QtGui.QPushButton(self.frame_3)
        self.bRePlot.setObjectName(_fromUtf8("bRePlot"))
        self.gridLayout.addWidget(self.bRePlot, 0, 8, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lShowStretch = QtGui.QLabel(self.tab_2)
        self.lShowStretch.setScaledContents(True)
        self.lShowStretch.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowStretch.setObjectName(_fromUtf8("lShowStretch"))
        self.gridLayout_4.addWidget(self.lShowStretch, 0, 1, 1, 1)
        self.lStretch = QtGui.QLabel(self.tab_2)
        self.lStretch.setObjectName(_fromUtf8("lStretch"))
        self.gridLayout_4.addWidget(self.lStretch, 1, 0, 1, 1)
        self.sldStretch = QtGui.QSlider(self.tab_2)
        self.sldStretch.setMinimum(-1000)
        self.sldStretch.setMaximum(1000)
        self.sldStretch.setPageStep(1)
        self.sldStretch.setOrientation(QtCore.Qt.Horizontal)
        self.sldStretch.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sldStretch.setTickInterval(100)
        self.sldStretch.setObjectName(_fromUtf8("sldStretch"))
        self.gridLayout_4.addWidget(self.sldStretch, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(205, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 2, 1, 1)
        self.lShowShfit = QtGui.QLabel(self.tab_2)
        self.lShowShfit.setScaledContents(True)
        self.lShowShfit.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowShfit.setObjectName(_fromUtf8("lShowShfit"))
        self.gridLayout_4.addWidget(self.lShowShfit, 2, 1, 1, 1)
        self.lShift = QtGui.QLabel(self.tab_2)
        self.lShift.setObjectName(_fromUtf8("lShift"))
        self.gridLayout_4.addWidget(self.lShift, 3, 0, 1, 1)
        self.sldShift = QtGui.QSlider(self.tab_2)
        self.sldShift.setMinimum(-500)
        self.sldShift.setMaximum(500)
        self.sldShift.setPageStep(1)
        self.sldShift.setOrientation(QtCore.Qt.Horizontal)
        self.sldShift.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sldShift.setTickInterval(100)
        self.sldShift.setObjectName(_fromUtf8("sldShift"))
        self.gridLayout_4.addWidget(self.sldShift, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(205, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 332, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.bManFit = QtGui.QPushButton(self.tab_3)
        self.bManFit.setGeometry(QtCore.QRect(170, 180, 81, 31))
        self.bManFit.setObjectName(_fromUtf8("bManFit"))
        self.cbFunctionSelect = QtGui.QComboBox(self.tab_3)
        self.cbFunctionSelect.setGeometry(QtCore.QRect(50, 180, 91, 21))
        self.cbFunctionSelect.setObjectName(_fromUtf8("cbFunctionSelect"))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1026, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuSetting = QtGui.QMenu(self.menuBar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setObjectName(_fromUtf8("actionSetting"))
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Help.addAction(self.actionAbout)
        self.menuSetting.addAction(self.actionSetting)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cbFunctionSelect.setCurrentIndex(0)
        QtCore.QObject.connect(self.sldStretch, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lShowStretch.setNum)
        QtCore.QObject.connect(self.sldShift, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lShowShfit.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Whatever Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lShowTime.setText(QtGui.QApplication.translate("MainWindow", "3000", None, QtGui.QApplication.UnicodeUTF8))
        self.lTime2.setText(QtGui.QApplication.translate("MainWindow", "Time(msec):", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Data Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.lTime1.setText(QtGui.QApplication.translate("MainWindow", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.lEfit.setText(QtGui.QApplication.translate("MainWindow", "Efit:", None, QtGui.QApplication.UnicodeUTF8))
        self.lShot1.setText(QtGui.QApplication.translate("MainWindow", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.lShowShot.setText(QtGui.QApplication.translate("MainWindow", "100000", None, QtGui.QApplication.UnicodeUTF8))
        self.lShot2.setText(QtGui.QApplication.translate("MainWindow", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.bSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cRhoPsi.setItemText(0, QtGui.QApplication.translate("MainWindow", "rho", None, QtGui.QApplication.UnicodeUTF8))
        self.cRhoPsi.setItemText(1, QtGui.QApplication.translate("MainWindow", "psi", None, QtGui.QApplication.UnicodeUTF8))
        self.bRePlot.setText(QtGui.QApplication.translate("MainWindow", "rePlot", None, QtGui.QApplication.UnicodeUTF8))
        self.lShowStretch.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lStretch.setText(QtGui.QApplication.translate("MainWindow", "Stretch:", None, QtGui.QApplication.UnicodeUTF8))
        self.lShowShfit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lShift.setToolTip(QtGui.QApplication.translate("MainWindow", "SHIFT", None, QtGui.QApplication.UnicodeUTF8))
        self.lShift.setText(QtGui.QApplication.translate("MainWindow", "Shift:", None, QtGui.QApplication.UnicodeUTF8))
        self.sldShift.setToolTip(QtGui.QApplication.translate("MainWindow", "SHIFT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "data control", None, QtGui.QApplication.UnicodeUTF8))
        self.bManFit.setText(QtGui.QApplication.translate("MainWindow", "Manual Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFunctionSelect.setItemText(0, QtGui.QApplication.translate("MainWindow", "tanh_multi", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFunctionSelect.setItemText(1, QtGui.QApplication.translate("MainWindow", "tanh_0out", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFunctionSelect.setItemText(2, QtGui.QApplication.translate("MainWindow", "tsplfun", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "fit control", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSetting.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetting.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetting.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))

from mplCanvasWrapper import MplCanvasWrapper

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

