# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Aug 20 18:38:53 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1062, 560)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mplCanvas = MplCanvasWrapper(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplCanvas.sizePolicy().hasHeightForWidth())
        self.mplCanvas.setSizePolicy(sizePolicy)
        self.mplCanvas.setMinimumSize(QtCore.QSize(400, 250))
        self.mplCanvas.setObjectName(_fromUtf8("mplCanvas"))
        self.gridLayout_3.addWidget(self.mplCanvas, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_12.setVerticalSpacing(3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(177, 24, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lEfit = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEfit.sizePolicy().hasHeightForWidth())
        self.lEfit.setSizePolicy(sizePolicy)
        self.lEfit.setMinimumSize(QtCore.QSize(28, 30))
        self.lEfit.setMaximumSize(QtCore.QSize(28, 16777215))
        self.lEfit.setObjectName(_fromUtf8("lEfit"))
        self.horizontalLayout_4.addWidget(self.lEfit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lShot2 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lShot2.sizePolicy().hasHeightForWidth())
        self.lShot2.setSizePolicy(sizePolicy)
        self.lShot2.setMinimumSize(QtCore.QSize(37, 0))
        self.lShot2.setMaximumSize(QtCore.QSize(37, 16777215))
        self.lShot2.setObjectName(_fromUtf8("lShot2"))
        self.horizontalLayout_3.addWidget(self.lShot2)
        self.lShowShot = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lShowShot.sizePolicy().hasHeightForWidth())
        self.lShowShot.setSizePolicy(sizePolicy)
        self.lShowShot.setMinimumSize(QtCore.QSize(60, 0))
        self.lShowShot.setMaximumSize(QtCore.QSize(60, 22))
        self.lShowShot.setFrameShape(QtGui.QFrame.Panel)
        self.lShowShot.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowShot.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowShot.setObjectName(_fromUtf8("lShowShot"))
        self.horizontalLayout_3.addWidget(self.lShowShot)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lTime2 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lTime2.sizePolicy().hasHeightForWidth())
        self.lTime2.setSizePolicy(sizePolicy)
        self.lTime2.setMinimumSize(QtCore.QSize(88, 0))
        self.lTime2.setMaximumSize(QtCore.QSize(88, 16777215))
        self.lTime2.setObjectName(_fromUtf8("lTime2"))
        self.horizontalLayout_2.addWidget(self.lTime2)
        self.lShowTime = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lShowTime.sizePolicy().hasHeightForWidth())
        self.lShowTime.setSizePolicy(sizePolicy)
        self.lShowTime.setMinimumSize(QtCore.QSize(50, 0))
        self.lShowTime.setMaximumSize(QtCore.QSize(50, 22))
        self.lShowTime.setFrameShape(QtGui.QFrame.Panel)
        self.lShowTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowTime.setObjectName(_fromUtf8("lShowTime"))
        self.horizontalLayout_2.addWidget(self.lShowTime)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(61, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.bRePlot = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRePlot.sizePolicy().hasHeightForWidth())
        self.bRePlot.setSizePolicy(sizePolicy)
        self.bRePlot.setMaximumSize(QtCore.QSize(66, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AquaBase"))
        self.bRePlot.setFont(font)
        self.bRePlot.setObjectName(_fromUtf8("bRePlot"))
        self.gridLayout_5.addWidget(self.bRePlot, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.cPlotToggle = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cPlotToggle.sizePolicy().hasHeightForWidth())
        self.cPlotToggle.setSizePolicy(sizePolicy)
        self.cPlotToggle.setMinimumSize(QtCore.QSize(66, 0))
        self.cPlotToggle.setMaximumSize(QtCore.QSize(66, 16777215))
        self.cPlotToggle.setObjectName(_fromUtf8("cPlotToggle"))
        self.cPlotToggle.addItem(_fromUtf8(""))
        self.cPlotToggle.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cPlotToggle, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem3 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.bSave = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSave.sizePolicy().hasHeightForWidth())
        self.bSave.setSizePolicy(sizePolicy)
        self.bSave.setMaximumSize(QtCore.QSize(66, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AquaBase"))
        self.bSave.setFont(font)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.gridLayout.addWidget(self.bSave, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 0, 2, 2, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lShowEfitTree = QtGui.QLabel(self.frame_3)
        self.lShowEfitTree.setMinimumSize(QtCore.QSize(60, 0))
        self.lShowEfitTree.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lShowEfitTree.setFrameShape(QtGui.QFrame.Panel)
        self.lShowEfitTree.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowEfitTree.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowEfitTree.setObjectName(_fromUtf8("lShowEfitTree"))
        self.horizontalLayout_5.addWidget(self.lShowEfitTree)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lShowData = QtGui.QLabel(self.frame_3)
        self.lShowData.setMinimumSize(QtCore.QSize(60, 0))
        self.lShowData.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lShowData.setFrameShape(QtGui.QFrame.Panel)
        self.lShowData.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowData.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowData.setObjectName(_fromUtf8("lShowData"))
        self.horizontalLayout_7.addWidget(self.lShowData)
        self.gridLayout_10.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(43, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lShowChisq = QtGui.QLabel(self.frame_3)
        self.lShowChisq.setMaximumSize(QtCore.QSize(21, 22))
        self.lShowChisq.setFrameShape(QtGui.QFrame.Panel)
        self.lShowChisq.setFrameShadow(QtGui.QFrame.Sunken)
        self.lShowChisq.setText(_fromUtf8(""))
        self.lShowChisq.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowChisq.setObjectName(_fromUtf8("lShowChisq"))
        self.horizontalLayout_8.addWidget(self.lShowChisq)
        self.gridLayout_10.addLayout(self.horizontalLayout_8, 0, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(44, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 261, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.leWindowTime = QtGui.QLineEdit(self.layoutWidget)
        self.leWindowTime.setObjectName(_fromUtf8("leWindowTime"))
        self.horizontalLayout_6.addWidget(self.leWindowTime)
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 140, 261, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lNTimes = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lNTimes.sizePolicy().hasHeightForWidth())
        self.lNTimes.setSizePolicy(sizePolicy)
        self.lNTimes.setMinimumSize(QtCore.QSize(31, 0))
        self.lNTimes.setAlignment(QtCore.Qt.AlignCenter)
        self.lNTimes.setObjectName(_fromUtf8("lNTimes"))
        self.horizontalLayout_9.addWidget(self.lNTimes)
        self.listWindowTime = QtGui.QListWidget(self.layoutWidget1)
        self.listWindowTime.setObjectName(_fromUtf8("listWindowTime"))
        self.horizontalLayout_9.addWidget(self.listWindowTime)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 481, 66))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lStretch = QtGui.QLabel(self.layoutWidget2)
        self.lStretch.setObjectName(_fromUtf8("lStretch"))
        self.gridLayout_4.addWidget(self.lStretch, 0, 0, 1, 1)
        self.lShowStretch = QtGui.QLabel(self.layoutWidget2)
        self.lShowStretch.setMinimumSize(QtCore.QSize(47, 0))
        self.lShowStretch.setScaledContents(True)
        self.lShowStretch.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowStretch.setObjectName(_fromUtf8("lShowStretch"))
        self.gridLayout_4.addWidget(self.lShowStretch, 0, 1, 1, 1)
        self.sldStretch = QtGui.QSlider(self.layoutWidget2)
        self.sldStretch.setMinimum(-1000)
        self.sldStretch.setMaximum(1000)
        self.sldStretch.setPageStep(1)
        self.sldStretch.setOrientation(QtCore.Qt.Horizontal)
        self.sldStretch.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sldStretch.setTickInterval(100)
        self.sldStretch.setObjectName(_fromUtf8("sldStretch"))
        self.gridLayout_4.addWidget(self.sldStretch, 0, 2, 1, 1)
        self.pbAuto = QtGui.QPushButton(self.layoutWidget2)
        self.pbAuto.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbAuto.setObjectName(_fromUtf8("pbAuto"))
        self.gridLayout_4.addWidget(self.pbAuto, 0, 3, 1, 1)
        self.lShift = QtGui.QLabel(self.layoutWidget2)
        self.lShift.setObjectName(_fromUtf8("lShift"))
        self.gridLayout_4.addWidget(self.lShift, 1, 0, 1, 1)
        self.lShowShfit = QtGui.QLabel(self.layoutWidget2)
        self.lShowShfit.setMinimumSize(QtCore.QSize(47, 0))
        self.lShowShfit.setScaledContents(True)
        self.lShowShfit.setAlignment(QtCore.Qt.AlignCenter)
        self.lShowShfit.setObjectName(_fromUtf8("lShowShfit"))
        self.gridLayout_4.addWidget(self.lShowShfit, 1, 1, 1, 1)
        self.sldShift = QtGui.QSlider(self.layoutWidget2)
        self.sldShift.setMinimum(-500)
        self.sldShift.setMaximum(500)
        self.sldShift.setPageStep(1)
        self.sldShift.setOrientation(QtCore.Qt.Horizontal)
        self.sldShift.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sldShift.setTickInterval(100)
        self.sldShift.setObjectName(_fromUtf8("sldShift"))
        self.gridLayout_4.addWidget(self.sldShift, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(295, 177, 31, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pbConfirm = QtGui.QPushButton(self.tab_2)
        self.pbConfirm.setGeometry(QtCore.QRect(340, 172, 71, 27))
        self.pbConfirm.setObjectName(_fromUtf8("pbConfirm"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbFunctionSelect = QtGui.QComboBox(self.tab_3)
        self.cbFunctionSelect.setObjectName(_fromUtf8("cbFunctionSelect"))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.cbFunctionSelect.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbFunctionSelect, 0, 0, 1, 1)
        self.bManFit = QtGui.QPushButton(self.tab_3)
        self.bManFit.setObjectName(_fromUtf8("bManFit"))
        self.gridLayout_6.addWidget(self.bManFit, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(270, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 410, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 410, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1062, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuSetting = QtGui.QMenu(self.menuBar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setObjectName(_fromUtf8("actionSetting"))
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName(_fromUtf8("actionRestore"))
        self.menu_File.addAction(self.actionRestore)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Help.addAction(self.actionAbout)
        self.menuSetting.addAction(self.actionSetting)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cbFunctionSelect.setCurrentIndex(0)
        QtCore.QObject.connect(self.sldStretch, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lShowStretch.setNum)
        QtCore.QObject.connect(self.sldShift, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lShowShfit.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Whatever Name", None))
        self.label.setText(_translate("MainWindow", "Data Description:", None))
        self.lEfit.setText(_translate("MainWindow", "Efit:", None))
        self.lShot2.setText(_translate("MainWindow", "Shot:", None))
        self.lShowShot.setText(_translate("MainWindow", "100000", None))
        self.lTime2.setText(_translate("MainWindow", "Time(msec):", None))
        self.lShowTime.setText(_translate("MainWindow", "3000", None))
        self.bRePlot.setText(_translate("MainWindow", "rePlot", None))
        self.label_2.setText(_translate("MainWindow", "View as:", None))
        self.cPlotToggle.setItemText(0, _translate("MainWindow", "  rho", None))
        self.cPlotToggle.setItemText(1, _translate("MainWindow", "  psi", None))
        self.bSave.setText(_translate("MainWindow", "Save", None))
        self.label_3.setText(_translate("MainWindow", "EfitTree:", None))
        self.lShowEfitTree.setText(_translate("MainWindow", "None", None))
        self.label_4.setText(_translate("MainWindow", "Data:", None))
        self.lShowData.setText(_translate("MainWindow", "None", None))
        self.label_5.setText(_translate("MainWindow", "Chisq:", None))
        self.label_6.setText(_translate("MainWindow", " Windowing time (+&- msecs):", None))
        self.label_7.setText(_translate("MainWindow", "NTimes:", None))
        self.lNTimes.setText(_translate("MainWindow", "0", None))
        self.lStretch.setText(_translate("MainWindow", "Stretch:", None))
        self.lShowStretch.setText(_translate("MainWindow", "0", None))
        self.pbAuto.setText(_translate("MainWindow", "Auto", None))
        self.lShift.setToolTip(_translate("MainWindow", "SHIFT", None))
        self.lShift.setText(_translate("MainWindow", "Shift:", None))
        self.lShowShfit.setText(_translate("MainWindow", "0", None))
        self.sldShift.setToolTip(_translate("MainWindow", "SHIFT", None))
        self.label_8.setText(_translate("MainWindow", "=>", None))
        self.pbConfirm.setText(_translate("MainWindow", "Confirm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "data control", None))
        self.cbFunctionSelect.setItemText(0, _translate("MainWindow", "tanh_multi", None))
        self.cbFunctionSelect.setItemText(1, _translate("MainWindow", "tanh_0out", None))
        self.cbFunctionSelect.setItemText(2, _translate("MainWindow", "spline", None))
        self.bManFit.setText(_translate("MainWindow", "Manual Fit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "fit control", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menuSetting.setTitle(_translate("MainWindow", "&Settings", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "Alt+A", None))
        self.actionSetting.setText(_translate("MainWindow", "&Settings", None))
        self.actionSetting.setShortcut(_translate("MainWindow", "Alt+S", None))
        self.actionRestore.setText(_translate("MainWindow", "&Restore", None))
        self.actionRestore.setShortcut(_translate("MainWindow", "Alt+R", None))

from mplCanvasWrapper import MplCanvasWrapper

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

